steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/dtumlops-447711/dummy-docker-registry/dummy_image',
    '-f',
    'dockerfile.txt'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/dtumlops-447711/dummy-docker-registry/dummy_image'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
  